MAIN_URL = 'https://windows10spotlight.com/page/'
DETAIL_PAGE_XPATH = '//*[@id="content"]/article[SPLIT_HERE]/h2/a'
DETAIL_PAGE_IMG_XPATH = '/html/body/div[1]/div/main/article/div[1]/div[2]/figure/a/img'
DETAIL_PAGE_CAPTION_XPATH = '//*[@class="wp-caption-text"]'
ABS_PATH = '/home/jonathan/Learning/scraper/entries'
ID_PATH = '//*[@id="content"]/article/h1'